name: TheBestPlugin
version: @version@
main: minegame159.thebestplugin.TheBestPlugin
api-version: 1.14

depend:
  - WorldGuard
  - WorldEdit

commands:
  gmc:
    description: Sets your gamemode to creative.
    usage: /gmc
    permission: thebestplugin.change-gamemode

  gms:
    description: Sets your gamemode to survival.
    usage: /gms
    permission: thebestplugin.change-gamemode

  feed:
    description: Fills your hunger bar.
    usage: /feed
    permission: thebestplugin.feed

  heal:
    description: Heals you.
    usage: /heal
    permission: thebestplugin.heal

  kits:
    description: Opens a list of kits.
    usage: /kits

  createkit:
    description: Creates a new kit.
    usage: /createkit <name>

  kit:
    description: Gives you a kit.
    usage: /kit <name>

  deletekit:
    description: Deletes a kit.
    usage: /kit <name>

  spawn:
    description: Teleports you to spawn.
    usage: /spawn

  kitcreator:
    description: Teleports you to kit creator.
    usage: /kitcreator

  suicide:
    description: Kill yourself, don't be shy.
    usage: /sucide

  togglekitcreator:
    description: Toggles kit creator.
    usage: /togglekitcreator
    permission: thebestplugin.toggle-kitcreator

  stats:
    description: Shows server wide stats.
    usage: /stats

  cleararenas:
    description: Clears arenas.
    usage: /cleararenas
    permission: thebestplugin.clear-arenas

  duel:
    description: Sends duel request to a player.
    usage: /duel <username>

  nether:
    description: Teleports you to the nether.
    usage: /nether

  trashcan:
    description: Opens a trash can.
    usage: /trashcan

  cancelduel:
    description: Cancels your active duel request.
    usage: /cancelduel

  accept:
    description: Accepts a duel.
    usage: /accept <username>

  decline:
    description: Declines a duel.
    usage: /decline <username>